---
title: "Consulting Homework 10"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(knitr)
library(pwr)
```

#1. Sample size calculations. 
##a.
###i. Assuming a known SD

```{r echo=FALSE}
# Make Jamie's data table
pilot <- as.data.frame(rbind(c(1,1.81,3.55,8.28,10.33,6.7,13.28),
                             c(2,1.77,5,8.33,11.28,9.77,12.14),
                             c(3,2.09,NA,7.57,10.57,13.38,13.42),
                             c(4,1.09,NA,7.99,12.4,10.95,9.83),
                             c(5,1.66,3.81,7.94,10.46,16.32,11.54),
                             c(6,1.91,4.33,5.4,7.18,4.74,9.66),
                             c(7,1.31,1.28,6.71,6.25,17.13,7.52),
                             c(8,1.28,3.13,7.04,7.54,8.68,12.36)))
colnames(pilot) <- c("ID","2mg","5mg","10mg","15mg","20mg","30mg")
s <- sd(pilot$`2mg`)
```

```{r echo=FALSE}
kable(pilot, caption = "Total absorbed zinc (TAZ) by dose")
```

Using the SD for the 2 mg group, because both the low and high zinc content groups are expected to absorb < 2 mg per day (90% power, alpha = 0.05):
$$
n = \frac{\sigma^2(Z_{0.9}+Z_{0.975})^2}{(\text{detectable difference})^2}=\frac{0.3500204^2*(1.28+1.96)^2}{(0.6)^2}=\frac{1.286106}{0.36} = 3.572516
$$
So for 90% power to detect a difference in TAZ of 0.6 mg/day, assuming known variation, Jamie will need 4 participants in each group. 

Using pairwise differences in the 2mg group:
```{r}
diffs <- as.numeric(dist(pilot$`2mg`))
sd(diffs)
```

###ii. Assuming an unknown SD

```{r echo=FALSE}

```