---
title: "Theory Homework 6"
author: "Tim Vigers"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

3.36) Code from Mayla:
```{r 1}
##the sequences for where each equation applies
x1 <- seq(-1,5,1)
x2 <- seq(-1,1,0.05)
x3 <- seq(2, 4, 0.05)
x4 <- seq(1,5,0.05)

##the plots themselves for each sequence
plot(x1, 0*x1,type="p", col="blue",ylab="f(x)",ylim=c(0,2)) #ylim=c(0,0.1)
lines(x2,(63/4)*(x2^6-x2^8), col="red")
lines(x3,(63/4)*((x3-3)^6 - (x3-3)^8), col="green")
lines(x4,(63/8)*(((x4-3)/2)^6 - ((x4-3)/2)^8), col="purple")
```
\pagebreak

Scale and location shifts for a normal distribution:
```{r}
ylim=c(0,1.5)
plot(seq(-3,3,.1),dnorm(seq(-3,3,.1)),type="l",ylim=ylim,col = 1,xlab = "x",ylab = "f(x)")
lines(seq(-3,3,.1),dnorm(seq(-3,3,.1),mean=-2,sd=sqrt(.1)),type="l",col=2)
lines(seq(-3,3,.1),dnorm(seq(-3,3,.1),mean=2,sd=sqrt(.1)),type="l",col=3)
lines(seq(-3,3,.1),dnorm(seq(-3,3,.1),mean=0,sd=sqrt(0.5)),type="l",col=4)
legend(0, 1.5, legend=c("N(0,1)", "N(-2,1)","N(2,1)","N(0,0.5)"),col=c(1:4), lty=1,cex = 0.8)
```