---
title: "Methods Linear Algebra Homework"
author: "Tim Vigers"
date: "November 7, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Matrix Algebra
```{r}
library(MASS)
A <- matrix(c(3,2,4,2),ncol = 2,nrow = 2)
B <- matrix(c(1,2,3,4),ncol = 2,nrow = 2)
A
B
```

##a. 
$$
\text{A and B are both 2x2 matrices.}
$$

##b. 
$$
a_{12}\text{ is the element in the first row and second column of A, so }a_{12} = 4.
$$

##c. 
$$
A + B=
\begin{bmatrix}
(3+1) & (4+3)\\
(2+2) & (2+4)
\end{bmatrix}=
\begin{bmatrix}
4 & 7\\
4 & 6
\end{bmatrix}
$$

```{r}
A + B
```

##d. 
$$
A - B=
\begin{bmatrix}
(3-1) & (4-3)\\
(2-2) & (2-4)
\end{bmatrix}=
\begin{bmatrix}
2 & 1\\
0 & -2
\end{bmatrix}
$$

```{r}
A-B
```

##e. 
$$
AB=
\begin{bmatrix}
(3*1)+(4*2) & (3*3)+(4*4)\\
(2*1)+(2*2) & (2*3)+(2*4)
\end{bmatrix}=
\begin{bmatrix}
11 & 25\\
6 & 14
\end{bmatrix}
$$

```{r}
A%*%B
```

##f. 
$$
BA=
\begin{bmatrix}
(1*3)+(3*2) & (1*4)+(3*2)\\
(2*3)+(4*2) & (2*4)+(4*2)
\end{bmatrix}=
\begin{bmatrix}
9 & 10\\
14 & 16
\end{bmatrix}
$$

```{r}
B%*%A
```

##g. 
AB does not equal BA, which is expected because the commutative law does not apply to matrices. This is because multiplying matrices depends on the order of columns and rows.

##h.
$$
A^T = 
\begin{bmatrix}
3 & 2\\
4 & 2
\end{bmatrix}
$$

```{r}
t(A)
```

$$
A\text{ is not a symmetric matrix because } A \neq A^T
$$

##i. 
$$
AB = 
\begin{bmatrix}
11 & 25\\
6 & 14
\end{bmatrix}
\text{ and }
(AB)^T=
\begin{bmatrix}
11 & 6\\
25 & 14
\end{bmatrix}
$$
$$
A^T = 
\begin{bmatrix}
3 & 2\\
4 & 2
\end{bmatrix}
\text{ and }
B^T = 
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$
$$
B^TA^T = 
\begin{bmatrix}
(1*3)+(2*4) & (1*2)+(2*2)\\
(3*3)+(4*4) & (3*2)+(4*2)
\end{bmatrix}=
\begin{bmatrix}
11 & 6\\
25 & 14
\end{bmatrix}
$$

```{r}
t(A%*%B)
t(B)%*%t(A)
```

##j. 
$$
A^{-1} = \frac{1}{ad-bc}*
\begin{bmatrix}
d & -b\\
-c & a
\end{bmatrix}=\frac{1}{(2*3)-(2*4)}*
\begin{bmatrix}
2 & -4\\
-2 & 3
\end{bmatrix}
$$
$$
= 
\begin{bmatrix}
\frac{2}{-2} & \frac{-4}{-2}\\
\frac{-2}{-2} & \frac{3}{-2}
\end{bmatrix}=
\begin{bmatrix}
-1 & 2\\
1 & -\frac{3}{2}
\end{bmatrix}
$$

```{r}
ginv(A)
```

##k. 
$$
AA^{-1} = 
\begin{bmatrix}
3 & 4\\
2 & 2
\end{bmatrix}*
\begin{bmatrix}
-1 & 2\\
1 & -\frac{3}{2}
\end{bmatrix}=
\begin{bmatrix}
(3*(-1))+(4*1) & (3*2)+(4*(-\frac{3}{2}))\\
(2*(-1))+(2*1) & (2*2)+(2*(-\frac{3}{2}))
\end{bmatrix}
$$
$$
=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}=I
$$
\pagebreak

#2. Principal Component Analysis 4 Dummies: Eigenvectors, Eigenvalues and Dimension Reduction